[target.aarch64-linux-android]
ar = "/Users/yageek/Developer/github/chargeprice-rs/bindings/chargeprice-android/NDK/arm64/bin/aarch64-linux-android-ar"
linker = "/Users/yageek/Developer/github/chargeprice-rs/bindings/chargeprice-android/NDK/arm64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "/Users/yageek/Developer/github/chargeprice-rs/bindings/chargeprice-android/NDK/arm/bin/arm-linux-androideabi-ar"
linker = "/Users/yageek/Developer/github/chargeprice-rs/bindings/chargeprice-android/NDK/arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "/Users/yageek/Developer/github/chargeprice-rs/bindings/chargeprice-android/NDK/x86/bin/i686-linux-android-ar"
linker = "/Users/yageek/Developer/github/chargeprice-rs/bindings/chargeprice-android/NDK/x86/bin/i686-linux-android-clang"

[target.x86_64-linux-android]
ar = "/Users/yageek/Developer/github/chargeprice-rs/bindings/chargeprice-android/NDK/x86_64/bin/x86_64-linux-android-ar"
linker = "/Users/yageek/Developer/github/chargeprice-rs/bindings/chargeprice-android/NDK/x86_64/bin/x86_64-linux-android-clang"
