/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chargeprice.api.client;

public class Client {

    private final long innerClient;

    // Inner JNI helper
    private static native long createNewClient(String key);
    private static native void releaseClient(long ptr);

    public Client(String key) throws Throwable {

        // Allocate the inner JNI client
        innerClient = createNewClient(key);
        if (innerClient == 0) {
            throw new RuntimeException();
        }
    }

    public void close() {
        releaseClient(innerClient);
    }
}
